### ISSUE TITLE
issue linking to weekly stats

### ISSUE THREAD

**Issue by lbalceda** [Xzandro/Swag#3]
noticed you store a lot of stuff like guildID / region in local storage, so sharing a link to weekly stats doesn't seem to work. Since someone else's browser localstorage might be empty, missing guildID/region etc. they get a weird list including people not in guild. some screenshot examples:

https://gw.swop.one/wars/week/43554?week=13&year=2017

with localstorage (13 entries):
![image](https://cloud.githubusercontent.com/assets/601632/24584721/3139cd2e-172b-11e7-821f-32fbc95c71cd.png)

without localstorage (400 entries):
![image](https://cloud.githubusercontent.com/assets/601632/24584724/4a339184-172b-11e7-9acd-1bb78642dec5.png)

**Comment by Xzandro** [comment]
Yup, known problem. Didnt have time to implement that yet. Its a pretty low priority project for me so it might take a while.

**Comment by lbalceda** [comment]
I don't mind taking a stab at a PR to help out - do you have general idea of how you would implement?
