### ISSUE TITLE
Incorrect data in weekly stats

### ISSUE THREAD

**Issue by tdct12** [Xzandro/Swag#4]
As far as I can tell as of 8/9/17 the stats are completely just incorrect. I'm seeing team members with negative absences, people with high winrates who have not battled this week. Seems to be completely askew at the moment. I love the concept, thank you for the great tool 👍

**Comment by Xzandro** [comment]
Hi, you didnt really provide much data, so I cant really look into it. (it works for the guilds I know). That being said I currently dont play SW and this project needs a complete rewrite badly (including db structure), which I dont have time / motivation to do. Make sure that you upload the data frequently (at least daily).

**Comment by Xzandro** [comment]
Closing this issie since I rewrote some of the components and I dont know of any errors regarding false data.
