### ISSUE TITLE
Incorrect amount of battles logged

### ISSUE THREAD

**Issue by nutkaze** [Xzandro/Swag#6]
Hi Xzandro, thanks for your work on this, this is a useful tool that no one else seems to have considered building.

Currently, we have fought 3 wars for the week yet it lists that I have 18 wins? Did I do something wrong when logging the info?

Server **Global** and guild name is **Advent**. I am player **NuTkaZe**.

**Comment by Xzandro** [comment]
Seems fine if you won all of the fights. 3 Wars means 9 swords with 2 round each = 18 round wins.

**Comment by nutkaze** [comment]
Ah, I'm an idiot, sorry for wasting your time and thanks again.
